### ISSUE TITLE
Crashing when entering a level

### ISSUE THREAD

**Issue by KontrollFreek** [TheSillyDoggo/GeodeMenu#1]
![2024-01-26_21-10-32.txt](https://github.com/TheSillyDoggo/GeodeMenu/files/14070707/2024-01-26_21-10-32.txt)

**Comment by TheSillyDoggo** [comment]
This is the worst thing to try and fix because it only happens on android but I think I figured it out I'm just doing something so I can't fix it

**Comment by TheSillyDoggo** [comment]
Fixed in 1.0.2
