### ISSUE TITLE
can't load

### ISSUE THREAD

**Issue by Idkwhattoputformyusername** [TheSillyDoggo/GeodeMenu#13]
![Screenshot_20240613-111503](https://github.com/TheSillyDoggo/GeodeMenu/assets/168951159/3fe322c6-ffc3-4ad9-919b-2316b66e91f2)

**Comment by ProblemReporter745** [comment]
I've had this same problem

**Comment by MoiZes000** [comment]
Me too

**Comment by Idkwhattoputformyusername** [comment]
Ima close this issue cuz they already fixed it
