### ISSUE TITLE
[NOT A ISSUE JUST A REQUEST] pls read

### ISSUE THREAD

**Issue by Lilicogamer13** [TheSillyDoggo/GeodeMenu#157]
I saw that you guys added langueses to qolmod, i can help you guys to translate it to brazillian portuguese and normal portuguese
if you guys wanna help from me(ew that sounded narcist) to translate the mod to brazilian and normal portuguese, just comment on this issue

**Comment by VictorGabrielGames** [comment]
i'm already doing pt-BR, just call me on discord if you wanna help (@ygabril) and also, this is not the correct place, the correct one is https://github.com/TheSillyDoggo/QOLMod-Translations

**Comment by Lilicogamer13** [comment]
ok sorry

**Comment by VictorGabrielGames** [comment]
can you just send me a msg on discord?
