### ISSUE TITLE
Add startpos switcher

### ISSUE THREAD

**Issue by Matistan** [TheSillyDoggo/GeodeMenu#17]
can you pls add startswitcher? QOLmod is really awesome, however startpos switcher is necessary, it's one of the greatest mods

**Comment by chemreal** [comment]
he already made a separate mod of it, tho its only for windows and 32 bit android below version 2.206

he apparently wont update them either btw

**Comment by Matistan** [comment]
Why won't he update them? How do you know that?

**Comment by chemreal** [comment]
he told me directly, thesillydoggo is active on his discord server

i dont know ask him
