### ISSUE TITLE
(commit facfbcd) Platformer gamemodes breaks teleport portals

### ISSUE THREAD

**Issue by Kingminer7** [TheSillyDoggo/GeodeMenu#7]
Using a build on commit facfbcd, teleport portals break if i use the platformer gamemode cheat.

you probably already know but just fyi

10 seconds is too long for github so video link: https://youtu.be/xaeOTYaPxc0?si=L4fxhgB7bLRqp2bD

**Comment by TheSillyDoggo** [comment]
fixed in latest
