### ISSUE TITLE
[BUG] CPS counter green highlight not reset after death

### ISSUE THREAD

**Issue by Maulve** [TheSillyDoggo/GeodeMenu#86]
## Steps to reproduce

1. Hold into a death obstacle

## Video

https://github.com/user-attachments/assets/9b6416ab-9e85-4a95-9633-520c913ba58b

## Proposed fix

Set the label color to white on death / after respawn

**Comment by TheSillyDoggo** [comment]
Fixed in 1.6.5, Will release soon :3

**Comment by Maulve** [comment]
Great! Can confirm, it is fixed.
